[build]
  cmd = "go build -o ./tmp/server ./cmd/server"
  bin = "./tmp/server"
  include_ext = ["go", "sql"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000
  poll = true
  poll_interval = 500

[misc]
  clean_on_exit = true

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
