FROM golang:1.26-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev git

# Install air for hot reload
RUN go install github.com/air-verse/air@v1.52.3

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

COPY . .

CMD ["air", "-c", ".air.toml"]
